---
sidebar: sidebar 
permalink: configuration-analysis.html 
keywords: evs, well-architected, configuration analysis, best practices, recommendations 
summary: Workload Factory が Amazon Elastic VMware Service 構成を分析して問題を特定し、ベストプラクティスの推奨事項を提供する方法について説明します。 
---
= EVS構成の構成分析
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory は、Amazon Elastic VMware Service (EVS) の構成を定期的に分析し、ベストプラクティスとの不整合を特定します。その結果を活用して、パフォーマンス、コスト効率、コンプライアンスを向上させましょう。

主な機能は次のとおりです：

* 日次構成分析
* 自動ベストプラクティス検証
* プロアクティブな可観測性
* 洞察から行動へ




== 仕組み

Workload Factory は、Amazon FSx for NetApp ONTAP ファイルシステムの導入環境で実行されているワークロードを毎日分析します。この分析により、適切に設計された状態、インサイト、および推奨事項が提供されます。

日々の分析が完了すると、デプロイメントのWell-architectedダッシュボードに、構成が「最適化済み」または「最適化されていない」として表示されます。総合的な最適化スコア、カテゴリ別の構成の問題、および構成の問題と推奨事項の一覧が表示されます。構成の問題に関する推奨事項を確認できます。一部の問題はWorkload Factoryによって自動的に修正できますが、その他の問題は手動での介入が必要です。この場合、Workload Factoryは、推奨される変更を実装するのに役立つ詳細な手順を提供します。

ご使用の環境に適用されない構成の分析を無視することができます。これにより、不要なアラートや不正確な最適化結果を回避できます。特定の構成分析を無視すると、Workload Factory ではその構成が全体の最適化スコアに含められません。



== 重要な理由

Workload Factoryは、継続的な評価と推奨事項、および修復策を組み合わせることで、大規模なストレージ、データベース、およびVMware環境にベストプラクティスを適用します。Workload Factoryコンソールで適用される自動修正により、人的ミスが削減され、統一された管理が確保され、ワークロードインフラストラクチャ全体でパフォーマンスと信頼性が維持されます。



== 分析要件

完全な構成分析を行うには、以下の手順を実行する必要があります：

* リンクを関連付けます。リンク接続により、Workload Factoryはデータ保護やパフォーマンスなど、すべてのファイルシステム構成を分析できます。
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["既存のリンクを関連付ける方法、または新しいリンクを作成して関連付ける方法を学びます"]。

* VMwareワークロードに対する_表示、計画、分析_の権限を付与します。
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS アカウントに権限を付与する方法を説明します"^]

* AWS アカウントには、検出された Amazon Elastic VMware Service 環境が少なくとも 1 つ必要です。




== EVS ワークロードのベストプラクティスと推奨事項

Workload Factory は、適切に設計された Amazon Elastic VMware Service （EVS）ワークロードを運用するためのベストプラクティスと推奨事項を提供します。Well-Architected 分析では、EVS 構成を評価して、VMware 環境が信頼性、セキュリティ、運用の卓越性、コストの最適化、パフォーマンス効率に最適化されていることを確認します。VMware の Well-Architected ステータスタブでは、EVS 環境に Well-Architected のベストプラクティスを実装するのに役立つ分析情報と推奨事項が見つかります。

Well-Architected 分析では、フレームワークの次の柱である _信頼性_ と _セキュリティ_ に基づいて構成を分類します。



=== 信頼性

信頼性とは、障害が発生した場合でも、ワークロードが意図された機能を正確かつ一貫して実行することを保証するものです。

* *EVS環境の回復力*
+
EVS クラスタノードがパーティション配置グループ全体に適切に分散されていることを確認します。すべてのノードは、4 つ以上のパーティションで構成された単一のパーティション配置グループのメンバーである必要があります。パーティションを適切に配置することで、EVS クラスタノードが AWS アベイラビリティゾーン内の障害が分離された複数のハードウェアパーティションに分散されます。不整合により、パーティションに障害が発生した場合に、処理能力が大幅に低下したり、ダウンタイムが発生する可能性があります。





=== セキュリティ

セキュリティは、リスク評価と軽減戦略を通じて、データ、システム、資産を保護することを重視します。

* *クラスタノード管理*
+
EVS クラスタノードに適切な EC2 停止および終了保護が設定されていることを確認します。EVS ESXi ノードは、vCenter またはその他の VMware レベルの管理ツールを使用してのみ管理する必要があります。適切な EC2 レベルの保護がないと、EC2 コンソールからノードが誤って停止または終了される可能性があり、仮想マシンのデータが使用できなくなったり、データが失われたりする可能性があります。



.次の手順
link:view-evs-well-architected.html["適切に設計された構成を実装する"]
