---
sidebar: sidebar 
permalink: deploy-fsx-file-system-evs.html 
keywords: vm workloads, deploy fsx, deploy storage for vms, evs, elastic vmware service 
summary: 推奨されるFSx for ONTAPファイルシステム（場合によってはファイルシステム）がお客様の要件を正確に満たしていることを確認したら、ワークロードファクトリを使用してAWS環境にシステムを導入できます。 
---
= 推奨されるFSx for ONTAPファイルシステムを導入
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
推奨されるFSx for ONTAPファイルシステム（場合によっては複数のファイルシステム）が要件を正確に満たしていることを確認したら、ワークロードファクトリを使用してAWS環境にシステムを導入できます。

ワークロードファクトリーアカウントに追加したポリシーと権限に応じて、ワークロードファクトリーを使用してFSx for ONTAPファイルシステムを完全にデプロイできます（読み取り/書き込みモードを使用）。権限が少ない場合 (読み取り専用モード)、または権限がまったくない場合 (基本モード) は、Codebox の CloudFormation テンプレートを使用して、AWS に FSx for ONTAP ファイルシステムを自分でデプロイする必要があります。

.Amazon Elastic VMware Service へのデプロイメントの要件
* Amazon Elastic VMware Service サブスクリプションが必要です。
* AWS アカウントで FSx for ONTAP ファイルシステムを作成するには、必要な権限が必要です。


.手順
. [Review plan]ページの下部にある[Deploy]*を選択すると、[FSx for ONTAPファイルシステムの作成]ページが表示されます。
+
FSx for ONTAPファイルシステムを定義するフィールドのほとんどは、入力した情報に基づいて入力されますが、このページで入力する必要があるフィールドがいくつかあります。

+
[クイック作成]または[詳細作成]オプションを使用できます。高度な作成には、カスタマイズ可能ないくつかの追加のストレージパラメータが用意されています。 https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["この2つのオプションの詳細を見る"]です。

. 「ファイル システムの一般構成」セクションで、次の情報を入力します。
+
.. * AWSクレデンシャル*：FSx for ONTAPファイルシステムを直接作成するために必要な権限をワークロードファクトリに付与するクレデンシャルを選択または追加します。また、CodeboxからCloudFormationコードを選択し、AWSでFSx for ONTAPファイルシステムを自分でデプロイすることもできます。
.. *ファイルシステム名*：このFSx for ONTAPファイルシステムに使用する名前を入力します。
.. *タグ*: オプションで、この FSx for ONTAP ファイル システムを分類するためのタグを追加できます。


. [Network & security]セクションで、次の情報を入力します。
+
.. *リージョンと VPC*: FSx for ONTAP ファイルシステムをデプロイするリージョンと VPC を選択します。
.. *セキュリティグループ*（詳細作成のみ）: *詳細作成*オプションを使用する場合、FSx for ONTAP VPC のデフォルトのセキュリティグループを選択して、すべてのトラフィックが FSx for ONTAP ファイルシステムにアクセスできるようにします。新しいセキュリティグループを作成することも、既存のセキュリティグループを選択することもできます。
+
*セキュリティ グループ構成を EVS NFS データストアに合わせて調整する* オプションを有効にすると、ワークロード ファクトリーは EVS NFS データストアの設定に従ってセキュリティ グループを構成します。

+
セキュリティグループにインバウンドルールを追加することで、他のAWSサービスからのFSx for ONTAPファイルシステムへのアクセスを制限できます。これにより、開いているサービスの数が減ります。最小ポートとプロトコルは次のとおりです。

+
[cols="15,10,55"]
|===
| プロトコル | ポート | 目的 


| TCP、UDP | 一一一 | portmapper（NFS要求で使用されるポートをネゴシエートするために使用） 


| TCP、UDP | 635 | nfs mountd（NFSマウントヨウキュウノジュシン） 


| TCP、UDP | 2049 | NFSネットワークトラフィック 


| TCP、UDP | 4045 | Network Lock Manager（NLM、lockd）-ロック要求を処理します。 


| TCP、UDP | 4046 | Network Status Monitor（NSM、statd）-ロック管理のためにサーバがリブートされたことをNFSクライアントに通知します。 
|===
.. *可用性ゾーン*: 可用性ゾーンとサブネットを選択します。
+
AZ間トラフィックの課金を回避するには、VMware SDDCが導入されている場所と同じアベイラビリティゾーンを選択する必要があります。

.. *暗号化* (詳細作成のみ): *詳細作成* オプションを使用する場合、ドロップダウンから AWS 暗号化キー名を選択できます。
.. *NFS データストア アクセス* (詳細作成のみ): *詳細作成* オプションを使用する場合、すべてのホストがデータストアにアクセスできるかどうか、または EVS 管理ホストのみがデータストアにアクセスできるかどうかを選択できます。


. [File system details]セクションで、次の情報を入力します。
+
.. *ONTAP 資格情報*: ONTAP ユーザー名のパスワードを入力します。
.. * Storage VMクレデンシャル*（アドバンスト作成のみ）：Storage VMのパスワードを入力し、確認のためにもう一度入力します。このファイルシステムに固有のパスワードを指定することも、ONTAPクレデンシャルに入力したパスワードと同じパスワードを使用することもできます。


. [まとめ]セクションでは、VMware Migration Advisorがお客様の情報に基づいて設計したFSx for ONTAPファイルシステムとデータストアの構成を確認できます。
. FSx for ONTAPファイルシステムを導入するには、[作成]*を選択します。このプロセスには最大2時間かかることがあります。
+
オプションとして、Codebox ウィンドウで *CloudFormation にリダイレクト* を選択し、CloudFormation スタックを使用してファイルシステムと推奨される VM 構成を作成できます。

+
どちらの場合も、CloudFormationで作成の進行状況を監視できます。



.結果
FSx for ONTAPファイルシステムが導入されます。Codebox の AWS CloudFormation テンプレートを使用して、推奨される VM 構成を Amazon Elastic VMware Service 環境にデプロイできるようになりました。
