---
sidebar: sidebar 
permalink: deploy-fsx-file-system-evs.html 
keywords: vm workloads, deploy fsx, deploy storage for vms, evs, elastic vmware service 
summary: '推奨される FSx for ONTAPファイルシステム (場合によってはファイルシステム) が要件を正確に満たしていることを確認したら、Workload Factory を使用して AWS 環境にシステムをデプロイできます。' 
---
= 推奨されるFSx for ONTAPファイルシステムを導入
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
推奨される FSx for ONTAPファイルシステム (場合によっては複数のファイルシステム) が要件を正確に満たしていることを確認したら、Workload Factory を使用して AWS 環境にシステムをデプロイできます。

Workload Factory アカウントに追加したポリシーと権限に応じて、Workload Factory を使用して (読み取り/書き込みモードを使用して) FSx for ONTAPファイル システムを完全にデプロイできます。権限が少ない場合 (読み取り専用モード)、または権限がまったくない場合 (基本モード) は、Codebox の CloudFormation テンプレートを使用して、AWS に FSx for ONTAPファイルシステムを自分でデプロイする必要があります。



== 要件

* Amazon Elastic VMware Service サブスクリプションが必要です。
* AWS アカウントで FSx for ONTAP ファイルシステムを作成するには、必要な権限が必要です。




== 考慮事項

* [クイック作成]または[詳細作成]オプションを使用できます。高度な作成には、カスタマイズ可能ないくつかの追加のストレージパラメータが用意されています。 https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["この2つのオプションの詳細を見る"]です。
* 「Amazon Elastic VMware Service の設定」セクションでは、外部データストアに接続するための EVS 仮想化環境を選択できます。これにより、デプロイメントのベスト プラクティス オプションがいくつかのフィールドに自動的に入力されます。必要に応じてこれらのオプションを変更できます。




== 手順

. [Review plan]ページの下部にある[Deploy]*を選択すると、[FSx for ONTAPファイルシステムの作成]ページが表示されます。
+
FSx for ONTAPファイルシステムを定義するフィールドのほとんどは、入力した情報に基づいて入力されますが、このページで入力する必要があるフィールドがいくつかあります。

. 「ファイル システムの一般構成」セクションで、次の情報を入力します。
+
.. *AWS 認証情報*: FSx for ONTAPファイルシステムを直接作成するために必要な権限を Workload Factory に付与する認証情報を選択または追加します。  Codebox から CloudFormation コードを選択し、AWS に FSx for ONTAPファイルシステムを自分でデプロイすることもできます。
.. *ファイルシステム名*：このFSx for ONTAPファイルシステムに使用する名前を入力します。
.. *タグ*: オプションで、この FSx for ONTAP ファイル システムを分類するためのタグを追加できます。


. 「Amazon Elastic VMware Service 設定」セクションの「環境 ID」リストから、データストアが接続される EVS 環境を選択します。
+
これにより、次のフィールドが自動的に入力されます。

+
** *VPC*
** *アベイラビリティゾーン*
** *サブネット*
** *NFS データストア アクセス* セクションで、*EVS ホスト管理のみ* オプションを選択した場合、*EVS ホスト管理 (CIDR)* フィールドが自動的に入力されます。
** *データストア マウント オプション* セクションで、データストアを EVS クラスターにマウントすることを選択した場合、*EVS クラスター VMware vCenter アドレス* と *vSphere 管理者認証情報シークレット ARN* フィールドが自動的に入力されます。


. [Network & security]セクションで、次の情報を入力します。
+
.. *リージョンと VPC*: FSx for ONTAP ファイルシステムをデプロイするリージョンと VPC を選択します。
.. *セキュリティグループ*（詳細作成のみ）: *詳細作成*オプションを使用する場合、FSx for ONTAP VPC のデフォルトのセキュリティグループを選択して、すべてのトラフィックが FSx for ONTAP ファイルシステムにアクセスできるようにします。新しいセキュリティグループを作成することも、既存のセキュリティグループを選択することもできます。
+
*セキュリティ グループ構成を EVS NFS データストアに合わせて調整する* オプションを有効にすると、Workload Factory は EVS NFS データストアの設定に従ってセキュリティ グループを構成します。

+
セキュリティグループにインバウンドルールを追加することで、他のAWSサービスからのFSx for ONTAPファイルシステムへのアクセスを制限できます。これにより、開いているサービスの数が減ります。最小ポートとプロトコルは次のとおりです。

+
[cols="15,10,55"]
|===
| プロトコル | ポート | 目的 


| TCP、UDP | 一一一 | portmapper（NFS要求で使用されるポートをネゴシエートするために使用） 


| TCP、UDP | 635 | nfs mountd（NFSマウントヨウキュウノジュシン） 


| TCP、UDP | 2049 | NFSネットワークトラフィック 


| TCP、UDP | 4045 | Network Lock Manager（NLM、lockd）-ロック要求を処理します。 


| TCP、UDP | 4046 | Network Status Monitor（NSM、statd）-ロック管理のためにサーバがリブートされたことをNFSクライアントに通知します。 
|===
.. *可用性ゾーン*: 可用性ゾーンとサブネットを選択します。
+
AZ間トラフィックの課金を回避するには、VMware SDDCが導入されている場所と同じアベイラビリティゾーンを選択する必要があります。

.. *暗号化* (詳細作成のみ): *詳細作成* オプションを使用する場合、ドロップダウンから AWS 暗号化キー名を選択できます。
.. *NFS データストア アクセス* (詳細作成のみ): *詳細作成* オプションを使用する場合、すべてのホストがデータストアにアクセスできるかどうか、または EVS 管理ホストのみがデータストアにアクセスできるかどうかを選択できます。


. [File system details]セクションで、次の情報を入力します。
+
.. *ONTAP 資格情報*: ONTAP ユーザー名のパスワードを入力します。
.. * Storage VMクレデンシャル*（アドバンスト作成のみ）：Storage VMのパスワードを入力し、確認のためにもう一度入力します。このファイルシステムに固有のパスワードを指定することも、ONTAPクレデンシャルに入力したパスワードと同じパスワードを使用することもできます。


. 「EVS クラスター接続」セクションで、次の情報を入力します。
+
.. *データストアのマウント オプション*: オプションで、*データストアを EVS クラスターにマウント* オプションを有効にして、データストアを Amazon EVS クラスターに自動的に接続します。このオプションを選択すると、Workload Factory は、 ONTAP のベスト プラクティスの推奨事項と一致するように VMware ESXi ホスト設定を構成します。ファイル システムをデプロイする前に、*概要* セクションでプランの詳細を確認し、変更された設定を確認できます。
.. *EVS クラスター vSphere コンソールの詳細*: Amazon EVS に接続する VMware vCenter サーバーの IP アドレスまたは FQDN を入力します。
.. *vSphere 管理者認証情報のシークレット ARN*: vSphere 管理者認証情報のシークレット ARN を選択します。これらの資格情報は、データストアをマウントし、推奨される VMware 設定を構成するために使用されます。
+
このリージョンで Amazon EVS が利用できない場合、またはアカウントに利用可能なシークレット ARN のリストを取得する権限がない場合は、シークレット ARN 値を手動で入力できます。



. [まとめ]セクションでは、VMware Migration Advisorがお客様の情報に基づいて設計したFSx for ONTAPファイルシステムとデータストアの構成を確認できます。
. FSx for ONTAPファイルシステムを導入するには、[作成]*を選択します。このプロセスには最大2時間かかることがあります。
+
オプションとして、Codebox ウィンドウで *CloudFormation にリダイレクト* を選択し、CloudFormation スタックを使用してファイルシステムと推奨される VM 構成を作成できます。

+
どちらの場合でも、CloudFormation で作成の進行状況を監視できます。





== 結果

FSx for ONTAPファイルシステムが導入されます。Codebox の AWS CloudFormation テンプレートを使用して、推奨される VM 構成を Amazon Elastic VMware Service 環境にデプロイできるようになりました。
