---
sidebar: sidebar 
permalink: launch-migration-advisor-evs-manual.html 
keywords: overview, concepts, features, use case, workloads, how Workload Factory works, migration, manual, specification, deploy, deployment, plan 
summary: VMware プランニング センターにアクセスするには、 NetApp Workload Factory にログインします。  EVS のデプロイメント プランを手動で作成できます。 
---
= Amazon EVS のデプロイメントプランを手動で作成する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
VMware プランニング センターにアクセスするには、 NetApp Workload Factory にログインします。そこから、ニーズに合わせてカスタマイズされた Amazon EVS のデプロイメントプランまたは移行プランを手動で作成できます。

Workload Factory にアクセスするには、ユーザー名とパスワードが必要であることに注意してください。アクセス権がない場合は、今すぐアカウントを作成してください。説明書をご覧ください https://docs.netapp.com/us-en/workload-setup-admin/quick-start.html["ここをクリック"]。



== 環境要件を手動で指定して展開計画を作成する

Amazon Elastic VMware Service で仮想マシンの要件を手動で指定し、カスタマイズされた Amazon FSx for NetApp ONTAP ファイルシステムを外部データストアとして使用できます。

.要件
* Amazon Elastic VMware Service サブスクリプションが必要です。


.手順
. 次のいずれかを使用してWorkload Factoryにログインします。 https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^] 。
. オプションとして、Workload Factory コンソールから Workload Factory にアクセスした場合は、VMware ワークロード タイルから *VMware プランニング センター* を選択し、*VMware プランニング センター* を選択します。  VMware プランニング センターが表示されます。
. *EVS プランを手動で作成*を選択します。
. VM 環境の要件を入力します。
+
[NOTE]
====
次の VM 移行のパフォーマンス要件と推奨事項に留意してください。

** パフォーマンス上の理由から、VM インベントリには 10TiB 以上のストレージ容量が推奨されます。
** このデプロイメントに指定する必要な IOPS 数に応じて、Amazon Elastic VMware Service データストアには最小スループットが必要です。
** FSx for ONTAP ファイルシステムの構成に応じて、Amazon Elastic VMware Service 環境で最適なパフォーマンスを実現するために、最小限の数の外部データストアが必要になります。


====
. 準備ができたら、「*計画の確認*」を選択して移行計画を確認します。
. 計画をレビューします。各セクションを展開すると、プランの詳細が表示されます。
+
デフォルトでは、Workload Factory は移行計画を計画センターに保存します。ページの上部付近でこのオプションの選択を解除できます。

. オプションとして、移行計画に満足したら、[計画のエクスポート (PDF)] を選択して計画の詳細を PDF ドキュメントとしてダウンロードできます。
. 展開プランをプロビジョニングする準備ができたら、[*プロビジョニング*] を選択します。


link:deploy-fsx-file-system-evs.html["VMwareワークロードの導入推奨されるFSx for ONTAPファイルシステム"]です。
