---
settings:
  name: VMware workloads
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: VMwareワークロードのドキュメント
    url: "/index.html"
  - title: リリースノート
    entries:
    - title: 新機能
      url: "/whats-new.html"
  - title: はじめに
    entries:
    - title: VMware向けNetAppワークロードファクトリーの詳細
      url: "/learn-about-vmware-workloads.html"
    - title: Amazon EVS への移行クイックスタート
      url: "/quick-start-evs.html"
    - title: Amazon EC2への移行のクイックスタート
      url: "/quick-start-native.html"
    - title: クイックスタートガイド：VMware Cloud on AWSへの移行
      url: "/quick-start.html"
    - title: VMware プランニング センターをご覧ください
      url: "/explore-planning-center.html"
  - title: VMware プランニング センターを使用する
    entries:
    - title: VMインベントリデータをアップロードする
      url: "/upload-vm-inventory.html"
    - title: Amazon Elastic VMware Service への移行
      entries:
      - title: 節約方法を見る
        url: "/calculate-evs-savings.html"
      - title: 手動で展開計画を作成する
        url: "/launch-migration-advisor-evs-manual.html"
      - title: 移行アドバイザを使用して導入計画を作成
        url: "/launch-migration-advisor-evs.html"
      - title: 推奨されるFSx for ONTAPファイルシステムを導入
        url: "/deploy-fsx-file-system-evs.html"
    - title: Amazon EC2への移行
      entries:
      - title: 移行アドバイザを使用して導入計画を作成
        url: "/launch-onboarding-advisor-native.html"
      - title: 推奨されるFSx for ONTAPファイルシステムを導入
        url: "/deploy-fsx-file-system-native.html"
    - title: VMware Cloud on AWSへの移行
      entries:
      - title: 移行アドバイザを使用して導入計画を作成
        url: "/launch-onboarding-advisor.html"
      - title: 推奨されるFSx for ONTAPファイルシステムを導入
        url: "/deploy-fsx-file-system.html"
      - title: FSx for ONTAPをVMware Cloud on AWSに接続
        url: "/connect-sddc-to-fsx.html"
      - title: 新しいインフラへのデータ移行
        url: "/migrate-data.html"
  - title: 知識とサポート
    entries:
    - title: サポートに登録します
      url: "/support-registration.html"
    - title: ヘルプを表示します
      url: "/get-help.html"
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: NetApp Workload Factory
  repo: workload-family
