---
settings:
  name: VMware workloads
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: VMwareワークロードのドキュメント
    url: "/index.html"
  - title: リリースノート
    entries:
    - title: 新機能
      url: "/whats-new.html"
  - title: はじめに
    entries:
    - title: VMware向けBlueXP  ワークロードファクトリの詳細
      url: "/learn-about-vmware-workloads.html"
    - title: クイックスタートガイド：VMware Cloud on AWSへの移行
      url: "/quick-start.html"
    - title: Amazon EC2への移行のクイックスタート
      url: "/quick-start-native.html"
  - title: VMware Migration Advisorを使用する
    entries:
    - title: Amazon EC2への移行
      entries:
      - title: 現在のVM構成のキャプチャ
        url: "/capture-vm-configurations-native.html"
      - title: 移行アドバイザを使用して導入計画を作成
        url: "/launch-onboarding-advisor-native.html"
      - title: 推奨されるFSx for ONTAPファイルシステムを導入
        url: "/deploy-fsx-file-system-native.html"
    - title: VMware Cloud on AWSへの移行
      entries:
      - title: 現在のVM構成のキャプチャ
        url: "/capture-vm-configurations.html"
      - title: 移行アドバイザを使用して導入計画を作成
        url: "/launch-onboarding-advisor.html"
      - title: 推奨されるFSx for ONTAPファイルシステムを導入
        url: "/deploy-fsx-file-system.html"
      - title: FSx for ONTAPをVMware Cloud on AWSに接続
        url: "/connect-sddc-to-fsx.html"
      - title: 新しいインフラへのデータ移行
        url: "/migrate-data.html"
  - title: 知識とサポート
    entries:
    - title: サポートに登録します
      url: "/support-registration.html"
    - title: ヘルプを表示します
      url: "/get-help.html"
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory
  repo: workload-family
