---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: Workload Factory の VMware 移行アドバイザー コンポーネントの新機能について説明します。 
---
= NetApp Workload Factory for VMware の新機能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory の VMware 移行アドバイザー コンポーネントの新機能について説明します。



== 2025年11月2日



=== FSx for ONTAPファイルシステムのデプロイメントウィザードに Amazon Elastic VMware Service の設定を導入

Amazon Elastic VMware Service の外部 NFS データストアとして使用する FSx for ONTAPファイル システムをデプロイするときに、データストアが接続される EVS 環境を選択できるようになりました。これにより、デプロイメント ウィザードのいくつかのフィールドが自動的に入力され、デプロイメント プロセスが簡素化されます。

https://docs.netapp.com/us-en/workload-vmware/deploy-fsx-file-system-evs.html["推奨されるFSx for ONTAPファイルシステムを導入"]



=== VMware ワークロードの権限の変更

VMware ワークロードでは、特定のアクションに必要な権限がより明確に示され、必要な権限のみを詳細に選択できます。資格情報を追加すると、以前の権限モデルである _読み取り専用_ と _読み取り/書き込み_ の代わりに、2 つの権限オプションから選択できるようになります。新しい権限モデルでは、権限ポリシーが次のように分割されます。

* _表示、計画、および分析_: EVS 仮想化環境のインベントリを表示し、システムの Well-Architected 分析を取得して、コスト削減を検討します。
* _データストアのデプロイと接続_: 推奨される VM レイアウトを Amazon EVS、Amazon EC2、または VMware Cloud on AWS vSphere クラスターにデプロイし、カスタマイズされたAmazon FSx for NetApp ONTAPファイルシステムを外部データストアとして使用します。


資格情報を追加するときに、VMware ワークロードに提供するアクセス レベルに基づいて、これらの権限ポリシーを 1 つ以上選択できます。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["ワークロードファクトリーの権限リファレンス"^]



=== Amazon EC2 Migration Advisorの機能強化

NetApp Workload Factory for VMware のこのリリースでは、移行アドバイザーのエクスペリエンスがいくつか改善されています。

* *移行計画の保存またはダウンロード*: 移行計画を PDF または CSV ファイルとして保存またはダウンロードできるようになりました。移行計画を保存すると、その計画は Workload Factory アカウントに保存されます。




== 2025年10月5日



=== BlueXP workload factoryがNetAppワークロードファクトリーに

BlueXP は、データ インフラストラクチャの管理における役割をより適切に反映するために、名前が変更され、再設計されました。その結果、 BlueXP workload factoryの名前がNetAppワークロード ファクトリーに変更されました。



=== VMware ワークロード プランニング センターのご紹介

VMware ワークロード プランニング センターを使用すると、VM インベントリと移行プランを 1 か所で表示および管理できます。異なる環境から複数の VM インベントリをアップロードして保存し、それらのいずれかについて AWS EC2 または Amazon Elastic VMware サービスへの移行の計画を開始できます。  AWS EC2 または EVS 移行プランを作成して保存することもできます。

https://docs.netapp.com/us-en/workload-vmware/explore-planning-center.html["VMware ワークロード プランニング センターの詳細"]



=== Amazon Elastic VMWare Service の移行アドバイザーサポートの導入

BlueXP Workload Factory for VMware では、Amazon Elastic VMware Service 移行アドバイザーを使用して、オンプレミスの VMware ワークロードを Amazon Elastic VMware Service に迅速に移行できるようになりました。移行アドバイザーを使用して移行計画を作成すると、計画センターの移行計画のリストに自動的に保存されます。

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs.html["移行アドバイザーを使用して Amazon EVS のデプロイメント計画を作成する"]



== 2025年8月3日



=== Amazon Elastic VMWare Service の移行アドバイザーのサポートが強化されました

NetApp Workload Factory は、Amazon FSx for NetApp ONTAPファイルシステムの自動デプロイメントとマウントをサポートするようになりました。これにより、Amazon EVS 環境への移行が完了したら、FSx for ONTAPファイルシステムに VM のデプロイを開始できるようになります。

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs-manual.html["移行アドバイザーを使用して Amazon EVS のデプロイメント計画を作成する"]



=== Amazon Elastic VMware Service への移行によるコスト削減額を計算する

VMware ワークロードを Amazon Elastic VMware Service (EVS) に移行することで得られる潜在的なコスト削減を検討できるようになりました。節約計算ツールを使用すると、基盤ストレージとしてAmazon FSx for NetApp ONTAP を使用した場合と使用しない場合の Amazon EVS のコストを比較できます。計算機は、環境の特性を調整すると、潜在的な節約額をリアルタイムで表示します。

https://docs.netapp.com/us-en/workload-vmware/calculate-evs-savings.html["BlueXP Workload Factory で Amazon Elastic VMware Service の割引価格をご確認ください"]



== 2025年6月29日



=== Amazon Elastic VMWare Service の移行アドバイザーサポートの導入

BlueXP Workload Factory for VMware は、Amazon Elastic VMware Service をサポートするようになりました。オンプレミスの VMware ワークロードを Amazon Elastic VMware Service に手動で移行することで、コストを最適化し、アプリケーションのリファクタリングや再プラットフォーム化を行わずに VMware 環境をより細かく制御できるようになります。

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs-manual.html["移行アドバイザーを使用して Amazon EVS のデプロイメント計画を作成する"]



== 2025年5月4日



=== Amazon EC2 Migration Advisorの機能強化

BlueXP Workload Factory for VMware のこのリリースでは、Amazon EC2 移行アドバイザーのエクスペリエンスが次のように改善されています。

* NetAppデータインフラのインサイトをデータソースとして*：ワークロードファクトリは、EC2移行アドバイザのデータコレクタを使用すると、NetAppデータインフラのインサイトに直接接続して、VMwareの導入情報を収集できるようになりました。

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["移行アドバイザを使用してAmazon EC2の導入計画を作成"]



=== 権限に関する用語を更新

Workload Factory のユーザー インターフェースとドキュメントでは、読み取り権限を示すために「読み取り専用」を使用し、自動化権限を示すために「読み取り/書き込み」を使用するようになりました。



== 2025年3月30日



=== Amazon EC2 Migration Advisorの機能強化

BlueXP Workload Factory for VMware のこのリリースでは、Amazon EC2 移行アドバイザーのエクスペリエンスがいくつか改善されています。

* *ボリューム割り当てガイダンスの強化*：EC2 Migration Advisorの「Classify」および「Package」ステップのボリューム割り当て情報には、読みやすさと操作性が向上しています。各ボリュームについて、より有益な情報が表示されるため、ボリュームの特定や割り当て方法の決定に役立ちます。
* *データコレクタスクリプトの効率化*: EC2移行アドバイザのデータコレクタスクリプトは、小規模なVM環境でデータを収集する際のCPU使用率を最適化します。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["移行アドバイザを使用してAmazon EC2の導入計画を作成"]



== 2025年3月2日



=== Amazon EC2 Migration Advisorの機能強化

BlueXP Workload Factory for VMware のこのリリースでは、Amazon EC2 移行アドバイザーのエクスペリエンスがいくつか改善されています。

* *推定インスタンスタイプ*：Migration Advisorで環境の要件を確認し、VMごとに推定Amazon EC2インスタンスタイプを提供できるようになりました。移行アドバイザの「スコープ」ステップで、各VMの推定インスタンスタイプを含めるように選択できます。
* * Amazon EBSボリュームの推奨機能*：移行アドバイザーは、特定のリージョンの容量やパフォーマンスのニーズに応じて、Amazon FSx for NetApp ONTAPではなくAmazon Elastic Block Store（EBS）にデータボリュームを移行することを推奨できるようになりました。
* *ファイルシステムの自動割り当ての強化*：Amazon FSx for NetApp ONTAPファイルシステムの割り当てが改善され、コストの最適化とスループットの最小化が実現しました。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["移行アドバイザを使用してAmazon EC2の導入計画を作成"]



== 2025年1月5日



=== Amazon EC2 Migration Advisorの機能強化

BlueXP Workload Factory for VMware のこのリリースでは、移行アドバイザーのエクスペリエンスがいくつか改善されています。

* *移行計画の保存またはダウンロード*: 移行計画を保存またはダウンロードし、移行計画を読み込んで移行アドバイザーに入力できるようになりました。移行計画を保存すると、その計画は Workload Factory アカウントに保存されます。
* *VM 選択の改善*: BlueXP Workload Factory for VMware では、移行展開に含める VM のリストのフィルタリングと検索がサポートされるようになりました。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["移行アドバイザを使用してAmazon EC2の導入計画を作成"]



== 2024年12月1日



=== Amazon EC2 Migration Advisorの機能強化

NetApp Workload Factory for VMware のこのリリースでは、移行アドバイザーのエクスペリエンスがいくつか改善されています。

* *データ収集*: BlueXP Workload Factory for VMware は、移行アドバイザーを使用する際に特定の期間のデータを収集する機能をサポートしています。
* *VM の選択*: BlueXP Workload Factory for VMware では、移行展開に含める VM の選択がサポートされるようになりました。
* *クイックエクスペリエンスと高度なエクスペリエンス*：Migration Advisorを使用すると、RVtoolsを使用したクイックマイグレーションエクスペリエンスまたはMigration Advisorデータコレクタを使用した高度なエクスペリエンスを選択できるようになりました。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["移行アドバイザを使用してAmazon EC2の導入計画を作成"]



== 2024年11月3日



=== VMware Migration Advisorによるデータ削減比率の向上

このリリースのWorkload Factory for VMwareには、データ削減比率アシスタントが搭載されています。データ削減比率アシスタントは、AWSクラウドのオンボーディングを準備する際に、VMwareのインベントリとストレージ資産に最適な比率を判断するのに役立ちます。

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["移行アドバイザを使用してAmazon EC2の導入計画を作成"]



== 2024年9月19日



=== VMware Migration Advisorの機能拡張

このリリースの Workload Factory for VMware では、機能性と安定性が強化されているほか、VMware 移行アドバイザーを使用する際に移行プランをインポートおよびエクスポートする機能も備わっています。

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["移行アドバイザを使用してAmazon EC2の導入計画を作成"]



== 2024年9月1日



=== Amazon EC2への移行

VMwareのワークロードファクトリでは、VMware Migration Advisorを使用したAmazon EC2への移行がサポートされるようになりました。



== 2024年7月7日



=== VMware向けWorkload Factoryの初期リリース

初期リリースには、VMware Migration Advisorを使用してオンプレミスのvSphere環境で現在の仮想マシン構成を分析し、推奨されるVMレイアウトをVMware Cloud on AWSに導入し、カスタマイズしたAmazon FSx for NetApp ONTAPファイルシステムを外部データストアとして使用するための計画を生成する機能が含まれています。
