---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: Workload FactoryのVMware Migration Advisorコンポーネントの新機能について説明します。 
---
= 新機能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload FactoryのVMware Cloud Migration Advisorコンポーネントの新機能について説明します。



== 2024年11月3日



=== VMware Migration Advisorによるデータ削減比率の向上

このリリースのWorkload Factory for VMwareには、データ削減比率アシスタントが搭載されています。データ削減比率アシスタントは、AWSクラウドのオンボーディングを準備する際に、VMwareのインベントリとストレージ資産に最適な比率を判断するのに役立ちます。

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["移行アドバイザを使用してAmazon EC2の導入計画を作成"]



== 2024年9月19日



=== VMware Migration Advisorの機能拡張

このリリースのWorkload Factory for VMwareには、機能と安定性が強化されたほか、VMware Migration Advisorを使用して移行計画をインポートおよびエクスポートできる機能があります。

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["移行アドバイザを使用してAmazon EC2の導入計画を作成"]



== 2024年9月1日



=== Amazon EC2への移行

Workload Factory for VMwareでは、VMware Migration Advisorを使用したAmazon EC2への移行がサポートされるようになりました。



== 2024年7月7日



=== Workload Factory for VMwareの初版リリース

初期リリースには、VMware Migration Advisorを使用してオンプレミスのvSphere環境で現在の仮想マシン構成を分析し、推奨されるVMレイアウトをVMware Cloud on AWSに導入し、カスタマイズしたAmazon FSx for NetApp ONTAPファイルシステムを外部データストアとして使用するための計画を生成する機能が含まれています。
